export SSH_ASKPASS=/usr/lib64/misc/ssh-askpass
export DOCK='sudo docker run -ti -v "$PWD"/artifacts:/usr/portage/packages sabayon/builder-amd64'
export DR=/var/www/localhost/htdocs/
export MW=$DR/w
  alias mw=MW
export WP=/var/www/localhost/htdocs/wp
  alias wp=WP
export WP_CON=$WP/wp-content
  alias WP_con=WP_CON
